services:
  postgres:
    container_name: postgres-information-security
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    networks:
      - default

  application:
    container_name: application-information-security
    build: .
    ports:
      - "8080:8080"
    networks:
      - default
    links:
      - postgres
networks:
    default:
        name: postgres-network

volumes:
    postgres-data:
      name: postgres-data
      driver: local