services:
  postgres:
    container_name: postgres-information-security
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"

  application:
    container_name: application-information-security
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

volumes:
    postgres-data:
      name: postgres-data
      driver: local